### ISSUE TITLE
version miss match

### ISSUE THREAD

**Issue by reckless-huang** [kcl-lang/kclvm-go#264]
error log 
````
(base) reckless@recklessdeMacBook-Pro myk8s % kcl main.k        
Init kcl runtime failed, path:  /usr/local
Tip: Have you used a binary version of KCL in your PATH that is not consistent with the KCL Go SDK? You can upgrade or reduce the KCL version or delete the KCL in your PATH
If not, you can run `rm -r /usr/local/bin` to fix this issue
panic: unexpected EOF: stderr = dyld[94858]: Library not loaded: @rpath/libkclvm_cli_cdylib.dylib
  Referenced from: <2CA48E8D-8E5A-31AA-9008-B3D2A90BB609> /usr/local/bin/kclvm_cli
  Reason: tried: '/usr/local/bin/../../../../../../../.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libkclvm_cli_cdylib.dylib' (no such file), '/usr/local/bin/libkclvm_cli_cdylib.dylib' (no such file), '/usr/local/bin/../../../../../../../.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libkclvm_cli_cdylib.dylib' (no such file), '/usr/local/bin/libkclvm_cli_cdylib.dylib' (no such file), '/usr/local/lib/libkclvm_cli_cdylib.dylib' (no such file), '/usr/lib/libkclvm_cli_cdylib.dylib' (no such file, not in dyld cache)


goroutine 1 [running]:
kcl-lang.io/kcl-go/pkg/runtime.initRuntime(0x0?)
        /home/runner/go/pkg/mod/kcl-lang.io/kcl-go@v0.8.2-0.20240318062820-ee6c53ee4781/pkg/runtime/init.go:72 +0x5d8
kcl-lang.io/kcl-go/pkg/runtime.GetRuntime.func1()
        /home/runner/go/pkg/mod/kcl-lang.io/kcl-go@v0.8.2-0.20240318062820-ee6c53ee4781/pkg/runtime/init.go:29 +0x20
sync.(*Once).doSlow(0x30?, 0x10a931420?)
        /opt/hostedtoolcache/go/1.21.8/x64/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.21.8/x64/src/sync/once.go:65
kcl-lang.io/kcl-go/pkg/runtime.GetRuntime()
        /home/runner/go/pkg/mod/kcl-lang.io/kcl-go@v0.8.2-0.20240318062820-ee6c53ee4781/pkg/runtime/init.go:29 +0x40
kcl-lang.io/kcl-go/pkg/service.NewKclvmServiceClient()
        /home/runner/go/pkg/mod/kcl-lang.io/kcl-go@v0.8.2-0.20240318062820-ee6c53ee4781/pkg/service/client_kclvm_service.go:21 +0x1c
kcl-lang.io/kcl-go/pkg/kcl.runWithHooks({0x14000f11578, 0x0, 0x0}, {0x10a8ebf90, 0x1, 0x1}, {0x14000f115e8, 0x1, 0x1})
        /home/runner/go/pkg/mod/kcl-lang.io/kcl-go@v0.8.2-0.20240318062820-ee6c53ee4781/pkg/kcl/api.go:378 +0xf4
kcl-lang.io/kcl-go/pkg/kcl.run(...)
        /home/runner/go/pkg/mod/kcl-lang.io/kcl-go@v0.8.2-0.20240318062820-ee6c53ee4781/pkg/kcl/api.go:387
kcl-lang.io/kcl-go/pkg/kcl.RunWithOpts({0x14000f115e8?, 0x1400089fe30?, 0x0?})
        /home/runner/go/pkg/mod/kcl-lang.io/kcl-go@v0.8.2-0.20240318062820-ee6c53ee4781/pkg/kcl/api.go:274 +0x50
kcl-lang.io/kpm/pkg/runner.(*Compiler).Run(...)
        /home/runner/go/pkg/mod/kcl-lang.io/kpm@v0.8.2/pkg/runner/runner.go:52
kcl-lang.io/kpm/pkg/client.(*KpmClient).Compile(0x140001c7c00, 0x14000a49858?, 0x14000f11750)
        /home/runner/go/pkg/mod/kcl-lang.io/kpm@v0.8.2/pkg/client/client.go:331 +0x158
kcl-lang.io/kpm/pkg/client.(*KpmClient).CompileWithOpts(0x140001c7c00, 0x140005281c0)
        /home/runner/go/pkg/mod/kcl-lang.io/kpm@v0.8.2/pkg/client/client.go:380 +0x4a4
kcl-lang.io/cli/pkg/options.(*RunOptions).Run(0x14000280700)
        /home/runner/work/cli/cli/pkg/options/run.go:155 +0x880
kcl-lang.io/cli/cmd/kcl/commands.NewRunCmd.func1(0x140009c0400?, {0x14000b0cf80?, 0x4?, 0x103ec60c5?})
        /home/runner/work/cli/cli/cmd/kcl/commands/run.go:49 +0x6c
github.com/spf13/cobra.(*Command).execute(0x1400086af00, {0x1400004c0b0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1400086af00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
kcl-lang.io/cli/cmd/kcl/commands.executeRunCmd({0x1400004c0b0, 0x1, 0x1})
        /home/runner/work/cli/cli/cmd/kcl/commands/plugin.go:17 +0x6c
kcl-lang.io/cli/cmd/kcl/commands.bootstrapCmdPlugin(0x14000804000?, {0x104baaa30, 0x1400088d428})
        /home/runner/work/cli/cli/cmd/kcl/commands/plugin.go:67 +0x3e8
kcl-lang.io/cli/cmd/kcl/commands.New()
        /home/runner/work/cli/cli/cmd/kcl/commands/root.go:126 +0x3d8
main.main()
        /home/runner/work/cli/cli/cmd/kcl/main.go:14 +0x1c
````

**Comment by Peefy** [comment]
May I ask how you installed KCL and kclvm_cli? You can delete `/usr/local/bin/kclvm_cli`

**Comment by reckless-huang** [comment]
> May I ask how you installed KCL and kclvm_cli? You can delete `/usr/local/bin/kclvm_cli`

cool is work
